#ifndef TokenType_H
#define TokenType_H
enum TokenType 
{
    NUM_DEC, NUM_INT, ID, STRING, COMMENT, RESERVED_KEYWORD, BINARY_OPERATOR, 
    OPEN_PAREN, CLOSE_PAREN, EQUALS, SEMICOLON, CODEBLOCK, ENDCODEBLOCK, SYMBOL, COMPARATOR_SYMBOLS, CHAR
};

#endif 
